---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# python-project-version-patch-action
name: '🐍 Patch the Python Project Version'
description: 'Replaces/updates the Python project version string'
# Note: works with both pyproject.toml and setup.py

inputs:
  # Mandatory
  replacement_version:
    description: 'Replacement project version string'
    required: true
    type: string
  path_prefix:
    description: 'Directory location containing project code'
    type: string
    required: false
    default: '.'

runs:
  using: 'composite'
  steps:
    - name: 'Verify valid directory path'
      shell: bash
      run: |
        # Verify valid directory path
        if [ ! -d "${{ inputs.path_prefix }}" ]; then
          echo "Error: invalid path/prefix to project directory ❌"; exit 1
        fi

    # yamllint disable-line rule:line-length
    - uses: lfreleng-actions/path-check-action@aa7dabfa92e50e31a0f091dd3e2741692e8dde07 # v0.1.5
      id: setup-py
      with:
        path: "${{ inputs.path_prefix }}/setup.py"

    # yamllint disable-line rule:line-length
    - uses: lfreleng-actions/path-check-action@aa7dabfa92e50e31a0f091dd3e2741692e8dde07 # v0.1.5
      id: pyproject-toml
      with:
        path: "${{ inputs.path_prefix }}/pyproject.toml"

    - name: "Patch Python project version: setup.py"
      id: patch-version-setup-py
      if: steps.setup-py.outputs.type == 'file'
      # yamllint disable-line rule:line-length
      uses: lfreleng-actions/file-sed-regex-action@e2c1c94d7936e1ded3e5fa8109416383f472ef7c # v0.1.2
      with:
        flags: '-i -E'
        # yamllint disable-line rule:line-length
        regex: 's:version=.*$:version="${{ inputs.replacement_version }}":;tx;q1;:x'

        path: "${{ inputs.path_prefix }}/setup.py"
        debug: true

    - name: "Patch Python project version: pyproject.toml"
      id: patch-version-pyproject-toml
      if: steps.pyproject-toml.outputs.type == 'file'
      # yamllint disable-line rule:line-length
      uses: lfreleng-actions/file-sed-regex-action@e2c1c94d7936e1ded3e5fa8109416383f472ef7c # v0.1.2
      with:
        flags: '-i -E'
        # yamllint disable-line rule:line-length
        regex: 's/^version =.*$/version = "${{ inputs.replacement_version }}"/;tx;q1;:x'
        path: "${{ inputs.path_prefix }}/pyproject.toml"
        debug: true
        # yamllint enable rule:line-length


    - name: "Validate results of string substitution"
      shell: bash
      run: |
        # Validate results of string substitution
        str=$(grep version test-python-project/pyproject.toml || true)
        if [ "$str" != "version = ${{ inputs.replacement_version }}" ]; then
          echo "Error: string substitution failed ❌"
          exit 1
        else
          echo "Version string substitution successful ✅"
        fi
