---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# python-project-version-patch-action
name: "🐍 Patches the Python Project Version"
description: "Replaces/updates the Python project metadata/version string"
# Note: works with both pyproject.toml and setup.py

inputs:
  REPLACEMENT_VERSION:
    description: "New project version string"
    required: true
    type: string
  PATH_PREFIX:
    description: "Directory location containing project code"
    type: string
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    # yamllint disable-line rule:line-length
    - uses: lfit/releng-reusable-workflows/.github/actions/path-check-action@9b845102d5158f0b80bd53405a0b6855b26dc4a0 # v0.2.9
      id: setup-py
      with:
        path: "${{ inputs.path_prefix }}setup.py"

    # yamllint disable-line rule:line-length
    - uses: lfit/releng-reusable-workflows/.github/actions/path-check-action@9b845102d5158f0b80bd53405a0b6855b26dc4a0 # v0.2.9
      id: pyproject-toml
      with:
        path: "${{ inputs.path_prefix }}pyproject.toml"

    - name: "Patch Python project version: setup.py"
      id: patch-version-setup-py
      if: steps.setup-py.outputs.type == 'file'
      # yamllint disable-line rule:line-length
      uses: lfreleng-actions/file-sed-regex-action@8b6ab94c60adb3d87bbc5ecd81fc3c55dc9516af # v0.1.0
      with:
        flags: "-i -E"
        regex: 's:version=.*$:version="${{ inputs.REPLACEMENT_VERSION }}":'
        path: "${{ inputs.path_prefix }}setup.py"

    - name: "Patch Python project version: pyproject.toml"
      id: patch-version-pyproject-toml
      if: steps.pyproject-toml.outputs.type == 'file'
      # yamllint disable-line rule:line-length
      uses: lfreleng-actions/file-sed-regex-action@8b6ab94c60adb3d87bbc5ecd81fc3c55dc9516af # v0.1.0
      with:
        flags: "-i -E"
        regex: 's:^version =.*$:version = "${{ inputs.REPLACEMENT_VERSION }}":'
        path: "${{ inputs.path_prefix }}pyproject.toml"
